version: '3.3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    command: >
      sh -c '
        echo "Waiting for Spring Boot...";
        until curl -s -f http://task-manager-1:8080/actuator/health > /dev/null; do
          echo "Still waiting...";
          sleep 2;
        done;
        echo "Spring Boot is up. Starting NGINX...";
        nginx -g "daemon off;";
      '
    ports:
      - "9090:80"
    env_file:
      - ~/.env.prod
    networks:
      - nsu-task-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - nsu-task-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - nsu-task-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.13
    container_name: filebeat
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - nsu-task-net

  grafana:
    container_name: grafana
    image: grafana/grafana:7.17.13
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret123
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - elasticsearch
    networks:
      - nsu-task-net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    env_file:
      - ~/.env.prod
    ports:
      - "15672:15672"
    networks:
      - nsu-task-net

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ~/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nsu-task-net

volumes:
  esdata:
  postgres_data:
  grafana-data:

networks:
  nsu-task-net:
    external: true