version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9090:80"
    env_file:
      - ~/.env.prod
    networks:
      - nsu-task-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - nsu-task-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - nsu-task-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.13
    container_name: filebeat
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - nsu-task-net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    env_file:
      - ~/.env.prod
    ports:
      - "15672:15672"
    networks:
      - nsu-task-net

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ~/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  esdata:
  postgres_data:

networks:
  nsu-task-net:
    driver: bridge