version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9090:80"
    env_file:
      - ~/.env.prod
    depends_on:
      - task-manager-1
      - task-manager-2

  task-planner-1:
    container_name: task-planner-1
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    depends_on:
      - rabbitmq
      - postgres
  task-planner-2:
    container_name: task-planner-2
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    depends_on:
      - rabbitmq
      - postgres
  task-planner-3:
    container_name: task-planner-3
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    depends_on:
      - rabbitmq
      - postgres
  task-planner-4:
    container_name: task-planner-4
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    depends_on:
      - rabbitmq
      - postgres

  task-manager-1:
    container_name: task-manager-1
    build:
      context: task-manager
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    depends_on:
      - rabbitmq
      - postgres
  task-manager-2:
    container_name: task-manager-2
    build:
      context: task-manager
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    depends_on:
      - rabbitmq
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.0
    container_name: filebeat
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    env_file:
      - ~/.env.prod
    ports:
      - "15672:15672"

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ~/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  esdata:
  postgres_data: