version: '3.3'

services:
  task-manager-1:
    container_name: task-manager-1
    build:
      context: task-manager
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    networks:
      - nsu-task-net
  task-manager-2:
    container_name: task-manager-2
    build:
      context: task-manager
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    networks:
      - nsu-task-net

  task-planner-1:
    container_name: task-planner-1
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    networks:
      - nsu-task-net
  task-planner-2:
    container_name: task-planner-2
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    networks:
      - nsu-task-net
  task-planner-3:
    container_name: task-planner-3
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    networks:
      - nsu-task-net
  task-planner-4:
    container_name: task-planner-4
    build:
      context: task-planner
      dockerfile: Dockerfile
    env_file:
      - ~/.env.prod
    labels:
      logging: "enabled"
    networks:
      - nsu-task-net

networks:
  nsu-task-net:
    external: true