apiVersion: 1
datasources:
  - name: elastic_logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    jsonData:
      index: "filebeat-*"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "log.level"