name: CI/CD Pipeline rc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build jars
        run: ./gradlew clean build -x test

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy project files to remote server
        run: |
          rsync -avz --delete --exclude='.git/' ./ root@194.58.46.63:/root/nsu-task-server

      - name: Deploy with Docker Compose
        run: |
          ssh root@194.58.46.63 "cd /root/nsu-task-server && \
            docker-compose -f docker-compose-production-services.yml down -v && \
            docker-compose -f docker-compose-production-services.yml pull && \
            docker-compose -f docker-compose-production-services.yml up -d --build"