name: CI/CD Gradle & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Установить JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Дать права на выполнение gradlew
        run: chmod +x gradlew
      - name: Сборка и тестирование Gradle
        run: ./gradlew clean build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Настройка SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Копирование файлов на сервер
        run: |
          scp -i ~/.ssh/id_rsa -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/${{ secrets.SSH_USER }}/app/
      - name: Деплой на сервере
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd /${{ secrets.SSH_USER }}/app && \
             docker-compose -f docker-compose-production.yml pull && \
             docker-compose -f docker-compose-production.yml up -d"